import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import LeftMenu from "../_components/LeftMenu";
import { UserProvider } from "~/context/userContext";
import { any } from "zod";
import { useState } from "react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <TRPCReactProvider cookies={cookies().toString()}>
            <LeftMenu />
            {children}
          </TRPCReactProvider>
        </UserProvider>
      </body>
    </html>
  );
}
